export const HOTEL_LIST = [
  {
    id: 'hotel_001',
    name: '北京丽思卡尔顿酒店',
    nameEn: 'The Ritz-Carlton Beijing',
    address: '北京市朝阳区建国路甲83号',
    starRating: 5,
    roomTypes: [
      {
        id: 'room_001',
        name: '豪华大床房',
        price: 1888,
        originalPrice: 2200,
        amenities: ['免费WiFi', '行政酒廊', '健身房'],
        maxOccupancy: 2,
        bedType: '2.0m大床',
        thumbnail: 'https://images.pexels.com/photos/16569268/pexels-photo-16569268.jpeg',
      },
      {
        id: 'room_002',
        name: '行政套房',
        description: '宽敞舒适的行政套房，享受专属服务',
        price: 3200,
        amenities: ['免费WiFi', '行政酒廊', '早餐', '泳池'],
        maxOccupancy: 3,
        bedType: '2.2m特大床',
      },
    ],
    price: 1888,
    lowestPrice: 1688,
    images: [
      'https://images.pexels.com/photos/16569268/pexels-photo-16569268.jpeg',
      'https://images.pexels.com/photos/16569268/pexels-photo-16569268.jpeg',
      'https://images.pexels.com/photos/16569268/pexels-photo-16569268.jpeg',
    ],
    thumbnail: 'https://images.pexels.com/photos/16569268/pexels-photo-16569268.jpeg',
    location: {
      city: '北京',
      district: '朝阳区',
      latitude: 39.9042,
      longitude: 116.4074,
    },
    amenities: ['免费WiFi', '停车场', '游泳池', 'SPA', '健身房', '餐厅'],
    isDiscount: true,
    discountInfo: '限时8折优惠',
    reviewScore: 4.8,
    reviewCount: 1256,
    tags: ['豪华', '商务', 'SPA', '亲子'],
    isOpen: true,
    createdAt: '2018-05-15',
    updatedAt: '2024-01-10',
  },

  {
    id: 'hotel_002',
    name: '上海外滩茂悦大酒店',
    nameEn: 'Hyatt on the Bund Shanghai',
    address: '上海市黄浦区黄浦路199号',
    starRating: 5,
    roomTypes: [
      {
        id: 'room_003',
        name: '江景大床房',
        price: 1588,
        amenities: ['免费WiFi', '江景', '早餐'],
        maxOccupancy: 2,
        bedType: '1.8m大床',
      },
      {
        id: 'room_004',
        name: '外滩套房',
        price: 2800,
        originalPrice: 3200,
        amenities: ['免费WiFi', '江景', '客厅', '早餐'],
        maxOccupancy: 4,
        bedType: '2.0m大床+1.5m单人床',
      },
    ],
    price: 1588,
    images: [
      'https://images.pexels.com/photos/16569268/pexels-photo-16569268.jpeg',
      'https://images.pexels.com/photos/16569268/pexels-photo-16569268.jpeg',
    ],
    thumbnail: 'https://images.pexels.com/photos/16569268/pexels-photo-16569268.jpeg',
    location: {
      city: '上海',
      district: '黄浦区',
      latitude: 31.2304,
      longitude: 121.4737,
    },
    amenities: ['免费WiFi', '停车场', '健身房', '餐厅', '会议室'],
    reviewScore: 4.6,
    reviewCount: 2341,
    tags: ['江景', '商务', '婚宴', '会议'],
    isOpen: true,
    createdAt: '2019-03-20',
    updatedAt: '2024-01-08',
  },

  {
    id: 'hotel_003',
    name: '杭州西湖国宾馆',
    address: '杭州市西湖区杨公堤18号',
    starRating: 4,
    roomTypes: [
      {
        id: 'room_005',
        name: '园景标准间',
        price: 688,
        amenities: ['免费WiFi', '花园景观', '早餐'],
        maxOccupancy: 2,
        bedType: '1.5m双床',
      },
      {
        id: 'room_006',
        name: '湖景豪华房',
        price: 988,
        originalPrice: 1188,
        amenities: ['免费WiFi', '湖景', '阳台', '早餐'],
        maxOccupancy: 2,
        bedType: '1.8m大床',
      },
    ],
    price: 688,
    lowestPrice: 588,
    location: {
      city: '杭州',
      district: '西湖区',
    },
    amenities: ['免费WiFi', '停车场', '花园', '茶室'],
    isDiscount: true,
    thumbnail: 'https://images.pexels.com/photos/16569268/pexels-photo-16569268.jpeg',
    discountInfo: '周末特惠立减100',
    reviewScore: 4.7,
    reviewCount: 856,
    tags: ['园林', '文化', '休闲', '摄影'],
    isOpen: true,
    createdAt: '2020-04-10',
  },

  {
    id: 'hotel_004',
    name: '深圳湾万豪酒店',
    nameEn: 'Marriott Hotel Shenzhen Bay',
    address: '深圳市南山区中心路3008号',
    starRating: 5,
    roomTypes: [
      {
        id: 'room_007',
        name: '商务大床房',
        price: 1288,
        amenities: ['免费WiFi', '商务中心', '健身房'],
        maxOccupancy: 2,
        bedType: '1.8m大床',
      },
    ],
    price: 1288,
    images: ['https://images.pexels.com/photos/16569268/pexels-photo-16569268.jpeg'],
    thumbnail: 'https://images.pexels.com/photos/16569268/pexels-photo-16569268.jpeg',
    location: {
      city: '深圳',
      district: '南山区',
      latitude: 22.5431,
      longitude: 113.9344,
    },
    amenities: ['免费WiFi', '停车场', '游泳池', '健身房', '商务中心'],
    reviewScore: 4.4,
    reviewCount: 967,
    tags: ['商务', '科技', '会展'],
    isOpen: false, // 暂时停业装修
    createdAt: '2017-11-01',
    updatedAt: '2024-01-05',
  },
];
